name: "Hello world workflow"

on:
  push:
  
jobs:
  print_date_ubuntu:
    name: Print Date Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Date Ubuntu!
        run: |
          echo 'Date Ubuntu'
          date
        
  print_date_windows:
    name: Print Date Windows!
    runs-on: windows-latest
    
    steps:
      - name: Print Date Windows!
        run: |
          echo 'Date Windows'
          date
        
  print_date_macos:
    name: Print Date MacOS!
    runs-on: macos-latest
      
    steps:
      - name: Print Date MacOS!
        run: |
          echo 'Date MacOS'
          date
          
    print_date_final:
      name: Print Date Final!
      runs-on: ubuntu-latest
      
      needs: 
        - print_date_ubuntu
        - print_date_windows
        - print_date_macos
      steps: 
      - name : Print Date Final!
        run: | 
        echo ' Date Final'
        date
        
